import { defineConfig } from 'vite'
import react from '@vitejs/react-refresh'
import tailwindcss from '@tailwindcss/vite'
import path from 'path'

export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: {
    proxy: {
      // Directs frontend state calls to read the shared JSON generated by backend
      '/agent_ui_state.json': {
        target: 'http://localhost:5173', // Fallback context
        configure: (proxy, options) => {
          proxy.on('configure', (proxy) => {
            // Serve static file straight from the root workspace folder if needed
          });
        }
      }
    }
  }
})